queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label=automerge

pull_request_rules:
  - name: automerge to main with label automerge and branch protection passing
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label=automerge
    actions:
      queue:
        name: default
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})
          {{ body }}
  - name: backport patches to v4.0.x branch
    conditions:
      - base=main
      - label=backport-to-v4.0.x
    actions:
      backport:
        branches:
          - release/v4.0.x
  - name: backport patches to v6.0.x branch
    conditions:
      - base=main
      - label=backport-to-v6.0.x
    actions:
      backport:
        branches:
          - release/v6.0.x
  - name: backport patches to v7.0.x branch
    conditions:
      - base=main
      - label=backport-to-v7.0.x
    actions:
      backport:
        branches:
          - release/v7.0.x
