# This workflow pushes new protobuf docker images on every change of Dockerfile.
#
# Images are pushed:
#
# osmolabs/fa-proto-gen:commit-hash    # is pushed
# osmolabs/fa-proto-gen:latest         # is updated
#
# All the images above have support for linux/amd64 and linux/arm64.

name: Push Protogen Images

on:
  push:
    paths:
      - "proto/Dockerfile"
jobs:
  feeapp-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: build_push_image
        uses: docker/build-push-action@v5
        with:
          file: proto/Dockerfile
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            osmolabs/fa-proto-gen:${{ github.sha }}
